[package]
name = "gtest-bug"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
gstd = { version = "1.5.0", features = ["debug"] }

[dev-dependencies]
gtest = "1.5.0"

[build-dependencies]
gear-wasm-builder = "1.5.0"
